name: Release Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile ai_moderator_fuyuka.py --name AiModeratorFuyuka.exe

      - name: Create config.json
        run: copy config.json.template config.json

      - name: Create release archive
        run: |
          $tagName = "${{ github.ref_name }}"
          $zipName = "AiModeratorFuyuka-$tagName.zip"
          Compress-Archive -Path dist\AiModeratorFuyuka.exe, LICENSE, README.md, config.json, images, messages, prompts -DestinationPath $zipName

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./AiModeratorFuyuka-${{ github.ref_name }}.zip
          asset_name: AiModeratorFuyuka-${{ github.ref_name }}.zip
          asset_content_type: application/zip
